/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MaintenanceRecordService } from "../maintenanceRecord.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MaintenanceRecordCreateInput } from "./MaintenanceRecordCreateInput";
import { MaintenanceRecord } from "./MaintenanceRecord";
import { MaintenanceRecordFindManyArgs } from "./MaintenanceRecordFindManyArgs";
import { MaintenanceRecordWhereUniqueInput } from "./MaintenanceRecordWhereUniqueInput";
import { MaintenanceRecordUpdateInput } from "./MaintenanceRecordUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MaintenanceRecordControllerBase {
  constructor(
    protected readonly service: MaintenanceRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MaintenanceRecord })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRecord",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMaintenanceRecord(
    @common.Body() data: MaintenanceRecordCreateInput
  ): Promise<MaintenanceRecord> {
    return await this.service.createMaintenanceRecord({
      data: {
        ...data,

        towerSite: data.towerSite
          ? {
              connect: data.towerSite,
            }
          : undefined,

        technician: data.technician
          ? {
              connect: data.technician,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        details: true,
        cost: true,

        towerSite: {
          select: {
            id: true,
          },
        },

        technician: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MaintenanceRecord] })
  @ApiNestedQuery(MaintenanceRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRecord",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async maintenanceRecords(
    @common.Req() request: Request
  ): Promise<MaintenanceRecord[]> {
    const args = plainToClass(MaintenanceRecordFindManyArgs, request.query);
    return this.service.maintenanceRecords({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        details: true,
        cost: true,

        towerSite: {
          select: {
            id: true,
          },
        },

        technician: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRecord",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async maintenanceRecord(
    @common.Param() params: MaintenanceRecordWhereUniqueInput
  ): Promise<MaintenanceRecord | null> {
    const result = await this.service.maintenanceRecord({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        date: true,
        details: true,
        cost: true,

        towerSite: {
          select: {
            id: true,
          },
        },

        technician: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRecord",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMaintenanceRecord(
    @common.Param() params: MaintenanceRecordWhereUniqueInput,
    @common.Body() data: MaintenanceRecordUpdateInput
  ): Promise<MaintenanceRecord | null> {
    try {
      return await this.service.updateMaintenanceRecord({
        where: params,
        data: {
          ...data,

          towerSite: data.towerSite
            ? {
                connect: data.towerSite,
              }
            : undefined,

          technician: data.technician
            ? {
                connect: data.technician,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          date: true,
          details: true,
          cost: true,

          towerSite: {
            select: {
              id: true,
            },
          },

          technician: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MaintenanceRecord })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MaintenanceRecord",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMaintenanceRecord(
    @common.Param() params: MaintenanceRecordWhereUniqueInput
  ): Promise<MaintenanceRecord | null> {
    try {
      return await this.service.deleteMaintenanceRecord({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          date: true,
          details: true,
          cost: true,

          towerSite: {
            select: {
              id: true,
            },
          },

          technician: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
