/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Equipment } from "./Equipment";
import { EquipmentCountArgs } from "./EquipmentCountArgs";
import { EquipmentFindManyArgs } from "./EquipmentFindManyArgs";
import { EquipmentFindUniqueArgs } from "./EquipmentFindUniqueArgs";
import { DeleteEquipmentArgs } from "./DeleteEquipmentArgs";
import { EquipmentService } from "../equipment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Equipment)
export class EquipmentResolverBase {
  constructor(
    protected readonly service: EquipmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Equipment",
    action: "read",
    possession: "any",
  })
  async _equipmentItemsMeta(
    @graphql.Args() args: EquipmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Equipment])
  @nestAccessControl.UseRoles({
    resource: "Equipment",
    action: "read",
    possession: "any",
  })
  async equipmentItems(
    @graphql.Args() args: EquipmentFindManyArgs
  ): Promise<Equipment[]> {
    return this.service.equipmentItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Equipment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Equipment",
    action: "read",
    possession: "own",
  })
  async equipment(
    @graphql.Args() args: EquipmentFindUniqueArgs
  ): Promise<Equipment | null> {
    const result = await this.service.equipment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Equipment)
  @nestAccessControl.UseRoles({
    resource: "Equipment",
    action: "delete",
    possession: "any",
  })
  async deleteEquipment(
    @graphql.Args() args: DeleteEquipmentArgs
  ): Promise<Equipment | null> {
    try {
      return await this.service.deleteEquipment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
